package com.tcoverwatch.feature.ping.persistence

import com.tcoverwatch.feature.ping.service.ServicePingRequest
import com.tcoverwatch.feature.ping.service.ServicePingResponse
import org.mapstruct.Mapper
import org.mapstruct.Mapping

// MapStruct boundary mapper: service DTOs <-> PingEntity.
// Implementation generated by kapt at compile time; Spring instantiates the
// generated class as a bean (`componentModel = "spring"`).
//
// Hibernate entities never escape this layer — the inputs/outputs of public
// methods here are exclusively service-layer DTOs.
@Mapper(componentModel = "spring")
interface PingEntityMapper {

    @Mapping(target = "id", ignore = true)
    fun toEntity(request: ServicePingRequest): PingEntity

    @Mapping(source = "message", target = "echo")
    fun toResponse(entity: PingEntity): ServicePingResponse
}
