apiVersion: v1
kind: Service
metadata:
  name: {{ include "tc-overwatch-server.fullname" . }}
  labels:
    {{- include "tc-overwatch-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "tc-overwatch-server.selectorLabels" . | nindent 4 }}
